extends Node

var browsecolumn = preload('res://BrowseColumn.tscn')


func _on_dict_arrived(arg):
	var dict = arg
	for i in $PanelContainer/Table.get_children():
		if i.clickable: i.queue_free()
	for x in dict.keys():
		var newone = browsecolumn.instance()
		for z in dict[x].keys():
			print(z)
			newone.get_node('HBoxContainer').get_node(z).text = str(dict[x][z])
		newone.connect("click",self,'_on_BrowseColumn_click')
		$PanelContainer/Table.add_child(newone)
	pass # Replace with function body.

signal click

func _on_BrowseColumn_click(arg):
	print('click1')
	emit_signal("click",arg)
	pass # Replace with function body.


func _on_Timer_timeout():
	if $PanelContainer.visible:
		get_parent().get_node("Loginetcode")._ask_server_for_server_list()
	pass # Replace with function body.
