extends Node

var sprite = preload('res://enemie/monster.tscn')

func _ready():
	for i in 1024:
		var add= sprite.instance()
		add.texture = get_node('../../Textures').dict[1]
		add.z_index = 1
		add_child(add)
#		add= sprite.instance()
#		add.texture = get_node('../../Textures').dict['Goblin2']
#		add.z_index = 2
#		add_child(add)
#		add= sprite.instance()
#		add.texture = get_node('../../Textures').dict['Goblin3']
#		add.z_index = 3
#		add_child(add)
#		add= sprite.instance()
#		add.texture = get_node('../../Textures').dict['Goblin4']
#		add.z_index = 4
#		add_child(add)
	pass # Replace with function body.
